apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert
spec:
  replicas: 5
  selector:
    matchLabels:
      app: convert
  template:
    metadata:
      labels:
        app: convert
    spec:
      containers:
      - name: convert
        image: vinisicius/conversao-temperatura:v1
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: convert
spec:
  selector:
    app: convert
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort